### ISSUE TITLE
Can you update source to v0.95?

### ISSUE THREAD

**Issue by keyscores** [d0minikk/materialize-meteor#11]
@d0minikk 
Thanks for maintaining this!

**Comment by keyscores** [comment]
Thanks! Doesn't seem to be updated on atmosphere yet...

**Comment by keyscores** [comment]
Can you please check atmosphere? Thanks!

**Comment by d0minikk** [comment]
updated! :)

**Comment by keyscores** [comment]
Thanks you rock!
Although I see @dogfalo updated to 95.1, any chance you can update again?
:D

Lucas Geiger

**Comment by keyscores** [comment]
Hello, just so you know, I tested 1.95.0 and it broke the navbar links, and footer css, on my meteor app. When I downgrade to 1.94.2 it restored functionality. Maybe you can check if the next version has this fixed?
