### ISSUE TITLE
Some selectors not working on 1.95.0

### ISSUE THREAD

**Issue by keyscores** [d0minikk/materialize-meteor#13]
- class="footer-copyright"
-  li - list items are not formatting
- navbar links not working

Maybe 1.95.1 fixes this?

**Comment by d0minikk** [comment]
hm, it's updated, you can try it now :)

**Comment by keyscores** [comment]
Hi there, the links in navbar are fixed, but the li tags in the footer are
still not formatting the same way as before.

Also, on mobile, the navbar does not close on click. Is there something
extra that should be done specific to meteor?

Lucas Geiger

**Comment by 0o-de-lally** [comment]
Fixed. you can close it. in 1.95.1 there is a specific selector called page-footer that was not
documented. The li tags are working now :)
