### ISSUE TITLE
Remove package from Atmosphere

### ISSUE THREAD

**Issue by splendido** [d0minikk/materialize-meteor#17]
There's now an official package for materialize: see [materialize:materialize](https://atmospherejs.com/materialize/materialize).

Since the authors of Materialize accepted the [Meteor Integration PR](https://github.com/Dogfalo/materialize/pull/640) and correctly registered the package on [autopublish.meteor.com](http://autopublish.meteor.com/) we'll have same day updates at every new release of Materialize CSS.

Please kindly unmigrate this package on atmosphere running the following from your terminal:

```
meteor admin set-unmigrated d0minikk:materialize-meteor
```

Thank you,
Luca

**Comment by d0minikk** [comment]
nice! :) 
I just unmigrated package.

**Comment by splendido** [comment]
Great, thanks!
