### ISSUE TITLE
Icons don't render

### ISSUE THREAD

**Issue by dragGH102** [d0minikk/materialize-meteor#20]
I tried both **menu** (which on official Material Design web site, to Materializecss refer to, is present) and **toc**

```
 <i class="material-icons">menu</i>
 <i class="material-icons">toc</i>
```

as explained at: http://materializecss.com/icons.html

I understand that it may be need to add

```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

but where? (since I'm not using Materializecss directory but as a Meteor module. Also I'm using iron:router which doesn't let me put <head> tag anywhere)

This renders instead

```
<i class="mdi-navigation-menu"></i>
```

from the example at: http://materializecss.com/side-nav.html

However this is documented nowhere (as far as I know).

**Comment by nigelpasco** [comment]
The link to the google icons api should go between the <head></head> section of your meteor project, generally found in index.html, or main.html.
You should have a <head> section as part of any meteor project to reference any meta tags, icons, project title etc.
