### ISSUE TITLE
Mobile Navbar on 1.94 not closing

### ISSUE THREAD

**Issue by keyscores** [d0minikk/materialize-meteor#8]
Seems like the navbar while mobile mode, is not collapsing after click/touch. It was working before I upgraded the package today. Seems to be an issue with iron router layouts. Any ideas?

**Comment by Dogfalo** [comment]
Upgrading to v0.94.2 should fix it.

**Comment by keyscores** [comment]
@d0minikk can you upgrade for this bugfix on atmosphere?
Thanks for the work by the way!

**Comment by d0minikk** [comment]
I just updated gh source and published on atmoshpere :)

**Comment by keyscores** [comment]
Thanks! It's mostly working. However when I click the link, it doesn't close the navigation. Can anyone else reproduce?
